"""
Liar's Deck Online - Packet Type Constants
Every C→S and S→C message type string lives here.
"""

# ── Client → Server ───────────────────────────────────────
C_CONNECT = "CONNECT"
C_RECONNECT = "RECONNECT"
C_JOIN_LOBBY = "JOIN_LOBBY"
C_LEAVE_LOBBY = "LEAVE_LOBBY"
C_PLAY_CARDS = "PLAY_CARDS"
C_CALL_LIAR = "CALL_LIAR"
C_ROULETTE_PULL = "ROULETTE_PULL"
C_PING = "PING"
C_CHAT = "CHAT"
C_READY = "READY"

# ── Server → Client ───────────────────────────────────────
S_WELCOME = "WELCOME"
S_RECONNECT_OK = "RECONNECT_OK"
S_RECONNECT_FAIL = "RECONNECT_FAIL"
S_LOBBY_JOINED = "LOBBY_JOINED"
S_MATCH_FOUND = "MATCH_FOUND"
S_GAME_STATE_UPDATE = "GAME_STATE_UPDATE"
S_YOUR_TURN = "YOUR_TURN"
S_PLAY_ACCEPTED = "PLAY_ACCEPTED"
S_PLAY_REJECTED = "PLAY_REJECTED"
S_LIAR_CALLED = "LIAR_CALLED"
S_REVEAL_CARDS = "REVEAL_CARDS"
S_ROULETTE_START = "ROULETTE_START"
S_ROULETTE_RESULT = "ROULETTE_RESULT"
S_ROUND_RESET = "ROUND_RESET"
S_GAME_OVER = "GAME_OVER"
S_OPPONENT_DISCONNECTED = "OPPONENT_DISCONNECTED"
S_OPPONENT_RECONNECTED = "OPPONENT_RECONNECTED"
S_PONG = "PONG"
S_ERROR = "ERROR"
S_CHAT_MSG = "CHAT_MSG"

# ── Lookup Sets ────────────────────────────────────────────
CLIENT_PACKET_TYPES = {
    C_CONNECT, C_RECONNECT, C_JOIN_LOBBY, C_LEAVE_LOBBY,
    C_PLAY_CARDS, C_CALL_LIAR, C_ROULETTE_PULL,
    C_PING, C_CHAT, C_READY,
}

SERVER_PACKET_TYPES = {
    S_WELCOME, S_RECONNECT_OK, S_RECONNECT_FAIL, S_LOBBY_JOINED,
    S_MATCH_FOUND, S_GAME_STATE_UPDATE, S_YOUR_TURN,
    S_PLAY_ACCEPTED, S_PLAY_REJECTED, S_LIAR_CALLED,
    S_REVEAL_CARDS, S_ROULETTE_START, S_ROULETTE_RESULT,
    S_ROUND_RESET, S_GAME_OVER,
    S_OPPONENT_DISCONNECTED, S_OPPONENT_RECONNECTED,
    S_PONG, S_ERROR, S_CHAT_MSG,
}

# ── Required Fields per Client Packet ─────────────────────
REQUIRED_FIELDS = {
    C_CONNECT: ["username"],
    C_RECONNECT: ["session_token", "player_id"],
    C_JOIN_LOBBY: [],
    C_LEAVE_LOBBY: [],
    C_PLAY_CARDS: ["card_indices", "claimed_type"],
    C_CALL_LIAR: [],
    C_ROULETTE_PULL: [],
    C_PING: [],
    C_CHAT: ["message"],
    C_READY: [],
}

